image: debian:buster

before_script:
  - apt-get update && apt-get install -y python3 python3-pip ninja-build flex bison gcc build-essential time
  - pip3 install meson

stages:
  - build

meson_build:
  stage: build
  script:
    - meson builddir
    - cd builddir
    - ninja test
    - chmod +w ../scripts/integration_tests
    - chmod +x ../scripts/run_integration_tests
    - ../scripts/run_integration_tests